name: Destroy AWS Infrastructure with Terraform

on:
  workflow_dispatch: # Triggered manually via GitHub Actions UI

env:
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  destroy:
    name: Destroy AWS Infrastructure
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 3: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Step 4: Initialize Terraform
    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform/

    # Step 5: Terraform Destroy
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: terraform/
